[package]
name = "webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web         = "4.10.2"
actix-multipart   = "0.6"
bcrypt            = "0.17.0"
chrono            = { version = "0.4.5", features = ["serde"] }
dotenv            =  "0.15.0"
futures-util      = "0.3"
jsonwebtoken      = "9.3.1"
log               = "0.4.26"
mongodb           = "3.2.3"
pnet              = "0.35.0"
pnet_packet       = "0.35.0"
pcap-parser       = "0.16.0"
regex             = "1.11.1"
reqwest           = { version = "0.11", features = ["json"] }
sanitize-filename = "0.5"
serde             = { version = "1.0.219", features = ["derive"]}
thiserror         = "2.0.12"
tokio             = {version = "1.44.0", features = ["full"]}
uuid              = { version = "1", features = ["v4", "serde"] }
sqlx              = { version = "0.8.3", features = ["chrono", "postgres", "uuid" , "runtime-tokio", "tls-native-tls"] }
rand = "0.8.5"


